name: Main CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build
        run: deno --unstable compile --allow-env=NODE_ENV -o dist/dicephrase src/main.ts

      - name: Publish binary
        uses: actions/upload-artifact@v2
        with:
          name: dicephrase-bin-${{ runner.os }}
          path: ./dist/dicephrase