// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Constants from "./constants"

var count_key = Constants.PHRASE_COUNT_KEY

var sep_key = Constants.SEPARATOR_KEY

var count_min = Constants.PHRASE_COUNT_MIN

var count_max = Constants.PHRASE_COUNT_MAX

var count_fallback = Constants.PHRASE_COUNT_FALLBACK

var sep_fallback = Constants.SEPARATOR_FALLBACK

var random_sep_chars = Constants.RANDOM_SEPARATOR_OPTS

export {
  count_key,
  sep_key,
  count_min,
  count_max,
  count_fallback,
  sep_fallback,
  random_sep_chars
}
/* count_key Not a pure module */
