FROM rust:1.73-buster AS builder
WORKDIR /_app

COPY ./apps/rusti/. /_app
RUN cargo build --bin server --release

FROM gcr.io/distroless/cc AS final
WORKDIR /_app

COPY --from=builder /_app/target/release/server /_app/

EXPOSE 8080
USER nonroot
CMD ["./server"]