[package]
name = "server"
version = "0.1.0"
edition = "2021"

# [workspace.dependencies]
# core-dicephrase="0.0.1"

[dependencies]
core-dicephrase = { path = "../core" }
dotenv = "0.15"
actix-web = "4"