// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_math from "rescript/lib/es6/js_math.js";

function make_wl_keys(count, getRandomValues) {
  var key_count = Math.imul(count, 5);
  var raw_bits = new Uint32Array(key_count);
  getRandomValues(raw_bits);
  var acc = [];
  var _idx = 0;
  while(true) {
    var idx = _idx;
    if (idx % 5 === 0) {
      acc.push(raw_bits.subarray(idx, idx + 5 | 0).map(function (x) {
                  return x % 6 + 1 | 0;
                }).join(""));
    }
    if ((idx + 1 | 0) === key_count) {
      return acc;
    }
    _idx = idx + 1 | 0;
    continue ;
  };
}

function shuffle(arr) {
  var items = arr;
  var len = arr.length;
  var idx = 0;
  while(len > 0) {
    len = len - 1 | 0;
    var rand = Math.random();
    idx = Js_math.floor_int(rand * len);
    var t = items[len];
    items[len] = items[idx];
    items[idx] = t;
  };
  return items;
}

function combine_zip(a1, a2) {
  var a_size = a1.length;
  var out = [];
  var _idx = 0;
  while(true) {
    var idx = _idx;
    if (idx === a_size) {
      return out;
    }
    var a_item = a1[idx];
    out.push(a_item);
    var b_item = a2[idx];
    out.push(b_item);
    _idx = idx + 1 | 0;
    continue ;
  };
}

export {
  make_wl_keys ,
  shuffle ,
  combine_zip ,
  
}
/* No side effect */
