name = "dicephrase-api"
main = "./dist/cf-worker.mjs"
compatibility_date = "2022-11-12"
workers_dev = false
build = {command = "pnpm build-dev"}


[env.development.build]
command = "pnpm build-dev"

[env.stg.build]
command = "pnpm build-prod"

[env.production.build]
command = "pnpm build-prod"
