name = "dicephrase-api"
main = "./dist/cf-worker.mjs"
compatibility_date = "2023-09-22"
workers_dev = true
build = { command = "pnpm build-dev" }


[env.development.build]
command = "pnpm build-dev"

[env.stg.build]
command = "pnpm build-prod"

[env.production.build]
command = "pnpm build-prod"
