name: Deno CLI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.22.0

      - name: Build
        run: |
          cd ./apps/main-cli 
          deno run --no-check --allow-all ./make.ts

      - name: Publish binary
        uses: actions/upload-artifact@v2
        with:
          name: dicephrase-bin-${{ runner.os }}
          path: ./dist/dicephrase