name: Main CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install gen-utils dependencies
        uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 6.32.8
          run_install: |
            - recursive: false
              args: [--filter, ./pkgs/gen-utils, --frozen-lockfile, --prefer-offline]

      - name: Test
        run: pnpm --filter ./pkgs/gen-utils test
        env:
          IS_NET: true
          NODE_ENV: test

  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install linting dependencies
        uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 6.32.8
          run_install: |
            - recursive: false
              args: [--filter, ./apps/main, --frozen-lockfile, --prefer-offline]

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
            
      - name: Lint
        run: pnpm --filter ./apps/main lint

  type-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install TypeScript type checker dependencies
        uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 6.32.8
          run_install: |
            - recursive: false
              args: [--filter, ./apps/main, --frozen-lockfile, --prefer-offline]

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Type check
        run: pnpm --filter ./apps/main tc

