name: Main CI

on: [push]

env:
  PNPM_VERSION: 7.0.0
  NODE_VERSION: 16.15.0

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.2.1
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Cache pnpm modules
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ env.NODE_VERSION }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-${{ env.NODE_VERSION }}-

      - name: Install gen-utils dependencies
        uses: pnpm/action-setup@v2.2.1
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: |
            - recursive: false
              args: [--filter, './pkgs/gen-utils', --frozen-lockfile, --prefer-offline]

      - name: Test
        run: pnpm --filter ./pkgs/gen-utils test
        env:
          IS_NET: true
          NODE_ENV: test

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.2.1
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Cache pnpm modules
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-lint-${{ env.cache-name }}-${{ env.NODE_VERSION }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-lint-${{ env.cache-name }}-${{ env.NODE_VERSION }}-

      - name: Install linting dependencies
        uses: pnpm/action-setup@v2.2.1
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: |
            - recursive: false
              args: [--filter, './apps/main', --frozen-lockfile, --prefer-offline, --ignore-scripts]
            
      - name: Lint
        run: pnpm --filter ./apps/main lint

  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.2.1
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Cache pnpm modules
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-type-check-${{ env.cache-name }}-${{ env.NODE_VERSION }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-type-check-${{ env.cache-name }}-${{ env.NODE_VERSION }}-

      - name: Install TypeScript type checker dependencies
        uses: pnpm/action-setup@v2.2.1
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: |
            - recursive: false
              args: [--filter, './apps/main', --frozen-lockfile, --prefer-offline, --ignore-scripts]

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Type check
        run: pnpm --filter ./apps/main tc

