name: Build native Ocaml HTTP Server

on:
  pull_request:
    paths:
      - "apps/ocaml/**"
      - ".github/workflows/ocaml.yml"
  push:
    paths:
      - "apps/ocaml/**"
      - ".github/workflows/ocaml.yml"

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t dicephrase-ocaml-http-server --file ./apps/ocaml/Dockerfile.ocaml .
