name: Build native Ocaml HTTP Server

on:
  push:
    paths:
      - "apps/ocaml/**"
      - ".github/workflows/ocaml.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t dicephrase-ocaml-http-server-alpine --file ./apps/ocaml/Dockerfile.ocaml .
