name: Cloudflare pages deployment

on: [push]

env:
  PNPM_VERSION: 6.32.12
  NODE_VERSION: 16.15.1

jobs:
  build-and-deploy:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.2.1
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Cache pnpm modules
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-and-deploy-${{ env.cache-name }}-${{ env.NODE_VERSION }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-and-deploy-${{ env.cache-name }}-${{ env.NODE_VERSION }}-

      - name: Install build dependencies
        uses: pnpm/action-setup@v2.2.1
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: |
            - recursive: false
              args: [--filter, './apps/main', --frozen-lockfile, --prefer-offline]

      - name: Build and pre-render
        env:
          IS_NET: true
        run: pnpm --filter ./apps/main build

      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: dicephrase
          directory: ./apps/main/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}