name: Build native Ocaml HTTP Server

on:
  pull_request:
    paths:
      - "apps/rusti/**"
      - ".github/workflows/rust.yml"
  push:
    paths:
      - "apps/rusti/**"
      - ".github/workflows/rust.yml"

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t rust-http-server --file ./apps/rusti/Dockerfile.http-server .
